#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE ROLE fedora3 LOGIN PASSWORD '$FEDORA_DB_PASSWORD';
  CREATE DATABASE fedora3 WITH ENCODING='UTF8';
  GRANT ALL PRIVILEGES ON DATABASE fedora3 TO fedora3;
EOSQL
